@TestController_HostAddress = http://localhost:3001

GET {{TestController_HostAddress}}/test/
Accept: application/json

###

GET {{TestController_HostAddress}}/test/100
Accept: application/json

###

GET {{TestController_HostAddress}}/test/0
Accept: application/json

### Register New User
POST {{TestController_HostAddress}}/api/account/create
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "user",
    "email" : "test2@exemple.com",
    "password": "StrongPassword123!",
    "passwordConfirm": "StrongPassword123!"
}